name: industrial_ci

on:
  push:
    paths-ignore:
    - '**.md'
  pull_request:
    paths-ignore:
    - '**.md'
  schedule:
    - cron: "0 2 * * 0" # Weekly on Sundays at 02:00

jobs:
  industrial_ci:
    strategy:
      matrix:
        ROS_DISTRO: [jazzy]
        ROS_REPO: [ros]
        AFTER_SETUP_TARGET_WORKSPACE: [apt update && apt install -y git gcc-11 g++-11]
    env:
      CCACHE_DIR: "${{ github.workspace }}/.ccache" # ccache directory

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: "ros-industrial/industrial_ci@master"
        env:
          ROS_DISTRO: ${{matrix.ROS_DISTRO}}
          ROS_REPO: ${{matrix.ROS_REPO}}
          AFTER_SETUP_TARGET_WORKSPACE: ${{matrix.AFTER_SETUP_TARGET_WORKSPACE}}
